directories:
  output: installer
  buildResources: build
appId: com.adamajroudi.anchor
productName: Anchor
files:
  - filter:
      - dist/**/*
      - src/**/*.html
      - src/**/*.css
      - images/**/*
      - assets/**/*
      - node_modules/**/*
win:
  target: nsis
  icon: assets/anchor.ico
  signAndEditExecutable: false
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  perMachine: false
  installerIcon: assets/anchor.ico
  uninstallerIcon: assets/anchor.ico
  installerHeaderIcon: assets/anchor.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Anchor
electronVersion: 30.5.1
